name: counter_app
 on :
    push :
     pull_request:
       branches:
        - master


jobs :
  build:
    name : Build
    runs-on : ubuntu-latest
 
    step :
      - name : Checkout code
        uses : actions/checkout@v3
      - name : Install Node 16
        uses : actions/setup-node@v3
        with :
          node-version : 16.x
      - name : Install dependencies
        run : npm i
       - name : build project
        run : npm run build
      - name : upload artifact in order to deploy
        uses : actions/upload -artifact@v2
        with :
           name: prodction-files
           path : ./build

deploy :
          name : deploy
          runs-on : ubuntu-latest
          needs : build

          step :
           -name: Download artifact
            user : actions/download-artifact@v2
            with :
                name: prodction-files
                path : ./build

          -name : Deploy to github pages
            user : peaceiris/actions-gh-pages@v3
            with :
                github_token: ${{secrets.GH_TOKEN}}
                pusblish_dir : ./build  


